name: tshirtsksa
description: TshirtsKSA mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^6.0.6
  # Service Locator
  get_it: ^5.0.1
  # Functional programming in Dart
  dartz: ^0.9.2
  # shared preferences
  shared_preferences: ^0.5.8
  #  Http client for Dart
  dio: ^3.0.10
  # compare objects
  equatable: ^1.2.5
  # adapting screen and font size
  flutter_screenutil: ^3.2.0
  # scroll component drop-down refresh
  pull_to_refresh: ^1.6.2
  # launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^5.7.8
  # text animations
  animated_text_kit: ^2.5.3
  #  A simple widget wrapper to enable modal progress HUD
  modal_progress_hud: ^0.1.3
  # This Flutter plugin provides an API for querying information about an application package.
  package_info: ^0.4.3+2
  # A pure dart toast Library.
  oktoast: ^2.3.2
  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.6.7+12

  # The Font Awesome Icon pack available as set of Flutter Icons.
  font_awesome_flutter: ^8.10.0
  # A Flutter plugin for finding commonly used locations on the filesystem. Supports iOS, Android,
  # Linux and MacOS. Not all methods are supported on all platforms.
  path_provider: ^1.6.24
  # We use the image_picker plugin to select images from the Android and iOS image library,
  # but it can't save images to the gallery. This plugin can provide this feature.
  image_gallery_saver: ^1.6.2
  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status.
  permission_handler: ^5.0.1+1
  # A simple plugin to capture widgets as Images.
  # This plugin wraps your widgets inside RenderRepaintBoundary
  screenshot: ^0.2.0
  # A Flutter plugin providing performance optimized signature canvas with ability to set custom
  # style, boundaries and initial state. This is native flutter implementation, so it supports all platforms.
  signature: ^3.2.0
  # A HSV(HSB)/HSL color picker inspired by chrome devtools and a material color picker for your flutter app.
  flutter_colorpicker: ^0.3.4


  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/png/error/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
